# Generated by Django 3.1.6 on 2021-11-25 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='is_removed', when={True})),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'db_table': 'pos_setting',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SettingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='is_removed', when={True})),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField(max_length=255, null=True)),
                ('value', models.TextField(max_length=255)),
                ('setting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='settings.setting')),
            ],
            options={
                'verbose_name': 'Setting Item',
                'verbose_name_plural': 'Settings Items',
                'db_table': 'pos_setting_item',
                'ordering': ['id'],
            },
        ),
    ]
